package mvc.model.dal.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * TblCategory generated by hbm2java
 */
public class TblCategory  implements java.io.Serializable {

     private Integer catId;
     private String catName;
     private String catDesc;
     private Boolean catStatus;
     private Set tblTransactions = new HashSet(0);

    public TblCategory() {
    }

    public TblCategory(String catName, String catDesc, Boolean catStatus, Set tblTransactions) {
       this.catName = catName;
       this.catDesc = catDesc;
       this.catStatus = catStatus;
       this.tblTransactions = tblTransactions;
    }
   
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public String getCatDesc() {
        return this.catDesc;
    }
    
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc;
    }
    public Boolean getCatStatus() {
        return this.catStatus;
    }
    
    public void setCatStatus(Boolean catStatus) {
        this.catStatus = catStatus;
    }
    public Set getTblTransactions() {
        return this.tblTransactions;
    }
    
    public void setTblTransactions(Set tblTransactions) {
        this.tblTransactions = tblTransactions;
    }
}