package mvc.model.dal.pojo;

import java.util.Date;

/**
 * TblTransaction generated by hbm2java
 */
public class TblTransaction  implements java.io.Serializable {


     private int traId;
     private TblCategory tblCategory;
     private TblConcept tblConcept;
     private TblAccount tblAccount;
     private Integer traNumber;
     private Double traBalance;
     private Date traDate;

    public TblTransaction() {
    }

	
    public TblTransaction(int traId) {
        this.traId = traId;
    }
    public TblTransaction(int traId, TblCategory tblCategory, TblConcept tblConcept, TblAccount tblAccount, Integer traNumber, Double traBalance, Date traDate) {
       this.traId = traId;
       this.tblCategory = tblCategory;
       this.tblConcept = tblConcept;
       this.tblAccount = tblAccount;
       this.traNumber = traNumber;
       this.traBalance = traBalance;
       this.traDate = traDate;
    }
   
    public int getTraId() {
        return this.traId;
    }
    
    public void setTraId(int traId) {
        this.traId = traId;
    }
    public TblCategory getTblCategory() {
        return this.tblCategory;
    }
    
    public void setTblCategory(TblCategory tblCategory) {
        this.tblCategory = tblCategory;
    }
    public TblConcept getTblConcept() {
        return this.tblConcept;
    }
    
    public void setTblConcept(TblConcept tblConcept) {
        this.tblConcept = tblConcept;
    }
    public TblAccount getTblAccount() {
        return this.tblAccount;
    }
    
    public void setTblAccount(TblAccount tblAccount) {
        this.tblAccount = tblAccount;
    }
    public Integer getTraNumber() {
        return this.traNumber;
    }
    
    public void setTraNumber(Integer traNumber) {
        this.traNumber = traNumber;
    }
    public Double getTraBalance() {
        return this.traBalance;
    }
    
    public void setTraBalance(Double traBalance) {
        this.traBalance = traBalance;
    }
    public Date getTraDate() {
        return this.traDate;
    }
    
    public void setTraDate(Date traDate) {
        this.traDate = traDate;
    }
}


