/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentation.view;

/**
 *
 * @author Diego SNP3004EX
 */
public class JFFConcept extends javax.swing.JFrame {

    /**
     * Creates new form JFFConcept
     */
    public JFFConcept() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_concept_catch = new javax.swing.JPanel();
        lbl_desc = new javax.swing.JLabel();
        jtf_desc = new javax.swing.JTextField();
        lbl_details = new javax.swing.JLabel();
        jscp_details = new javax.swing.JScrollPane();
        jtxt_details = new javax.swing.JTextArea();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        pnl_concept_show = new javax.swing.JPanel();
        jscp_concept = new javax.swing.JScrollPane();
        jtbl_concept = new javax.swing.JTable();
        mbar_concept = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_concept_catch.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del concepto"));
        pnl_concept_catch.setToolTipText("");

        lbl_desc.setText("Descripción");

        lbl_details.setText("Detalles");

        jtxt_details.setColumns(20);
        jtxt_details.setRows(5);
        jscp_details.setViewportView(jtxt_details);

        btn_save.setText("Agregar");

        btn_delete.setText("Eliminar");

        javax.swing.GroupLayout pnl_concept_catchLayout = new javax.swing.GroupLayout(pnl_concept_catch);
        pnl_concept_catch.setLayout(pnl_concept_catchLayout);
        pnl_concept_catchLayout.setHorizontalGroup(
            pnl_concept_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_concept_catchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_concept_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jscp_details)
                    .addComponent(lbl_desc)
                    .addComponent(lbl_details)
                    .addGroup(pnl_concept_catchLayout.createSequentialGroup()
                        .addComponent(jtf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_save)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnl_concept_catchLayout.setVerticalGroup(
            pnl_concept_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_concept_catchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_concept_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_concept_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_save)
                        .addComponent(btn_delete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_details)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscp_details, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbl_concept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción", "Detalles"
            }
        ));
        jscp_concept.setViewportView(jtbl_concept);

        javax.swing.GroupLayout pnl_concept_showLayout = new javax.swing.GroupLayout(pnl_concept_show);
        pnl_concept_show.setLayout(pnl_concept_showLayout);
        pnl_concept_showLayout.setHorizontalGroup(
            pnl_concept_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(pnl_concept_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jscp_concept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
        );
        pnl_concept_showLayout.setVerticalGroup(
            pnl_concept_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
            .addGroup(pnl_concept_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_concept_showLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jscp_concept, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        mbar_concept.add(jMenu1);

        setJMenuBar(mbar_concept);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_concept_show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_concept_catch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnl_concept_catch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_concept_show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFConcept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jscp_concept;
    private javax.swing.JScrollPane jscp_details;
    private javax.swing.JTable jtbl_concept;
    private javax.swing.JTextField jtf_desc;
    private javax.swing.JTextArea jtxt_details;
    private javax.swing.JLabel lbl_desc;
    private javax.swing.JLabel lbl_details;
    private javax.swing.JMenuBar mbar_concept;
    private javax.swing.JPanel pnl_concept_catch;
    private javax.swing.JPanel pnl_concept_show;
    // End of variables declaration//GEN-END:variables
}
