package presentation.model.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblAccount generated by hbm2java
 */
public class TblAccount  implements java.io.Serializable {


     private Integer accId;
     private TblAccounttype tblAccounttype;
     private String accNumber;
     private Integer accOwner;
     private Double accBalance;
     private Date accCreationdate;
     private Boolean accStatus;
     private Set tblTransactions = new HashSet(0);

    public TblAccount() {
    }

	
    public TblAccount(String accNumber) {
        this.accNumber = accNumber;
    }
    public TblAccount(TblAccounttype tblAccounttype, String accNumber, Integer accOwner, Double accBalance, Date accCreationdate, Boolean accStatus, Set tblTransactions) {
       this.tblAccounttype = tblAccounttype;
       this.accNumber = accNumber;
       this.accOwner = accOwner;
       this.accBalance = accBalance;
       this.accCreationdate = accCreationdate;
       this.accStatus = accStatus;
       this.tblTransactions = tblTransactions;
    }
   
    public Integer getAccId() {
        return this.accId;
    }
    
    public void setAccId(Integer accId) {
        this.accId = accId;
    }
    public TblAccounttype getTblAccounttype() {
        return this.tblAccounttype;
    }
    
    public void setTblAccounttype(TblAccounttype tblAccounttype) {
        this.tblAccounttype = tblAccounttype;
    }
    public String getAccNumber() {
        return this.accNumber;
    }
    
    public void setAccNumber(String accNumber) {
        this.accNumber = accNumber;
    }
    public Integer getAccOwner() {
        return this.accOwner;
    }
    
    public void setAccOwner(Integer accOwner) {
        this.accOwner = accOwner;
    }
    public Double getAccBalance() {
        return this.accBalance;
    }
    
    public void setAccBalance(Double accBalance) {
        this.accBalance = accBalance;
    }
    public Date getAccCreationdate() {
        return this.accCreationdate;
    }
    
    public void setAccCreationdate(Date accCreationdate) {
        this.accCreationdate = accCreationdate;
    }
    public Boolean getAccStatus() {
        return this.accStatus;
    }
    
    public void setAccStatus(Boolean accStatus) {
        this.accStatus = accStatus;
    }
    public Set getTblTransactions() {
        return this.tblTransactions;
    }
    
    public void setTblTransactions(Set tblTransactions) {
        this.tblTransactions = tblTransactions;
    }
}
