package presentation.model.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * TblAccounttype generated by hbm2java
 */
public class TblAccounttype  implements java.io.Serializable {


     private Integer actId;
     private String actName;
     private String actDesc;
     private Boolean actStatus;
     private Set tblAccounts = new HashSet(0);

    public TblAccounttype() {
    }

	
    public TblAccounttype(String actName) {
        this.actName = actName;
    }
    public TblAccounttype(String actName, String actDesc, Boolean actStatus, Set tblAccounts) {
       this.actName = actName;
       this.actDesc = actDesc;
       this.actStatus = actStatus;
       this.tblAccounts = tblAccounts;
    }
   
    public Integer getActId() {
        return this.actId;
    }
    
    public void setActId(Integer actId) {
        this.actId = actId;
    }
    public String getActName() {
        return this.actName;
    }
    
    public void setActName(String actName) {
        this.actName = actName;
    }
    public String getActDesc() {
        return this.actDesc;
    }
    
    public void setActDesc(String actDesc) {
        this.actDesc = actDesc;
    }
    public Boolean getActStatus() {
        return this.actStatus;
    }
    
    public void setActStatus(Boolean actStatus) {
        this.actStatus = actStatus;
    }
    public Set getTblAccounts() {
        return this.tblAccounts;
    }
    
    public void setTblAccounts(Set tblAccounts) {
        this.tblAccounts = tblAccounts;
    }
}


