/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mvc.view;

import java.net.URL;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego SNP3004EX
 */
public class JFFAccount extends javax.swing.JFrame {

    /**
     * Creates new form JFFAccount
     */
    public JFFAccount() {
        initComponents();
        
        URL url = getClass().getResource("/resource/img/wallet.png");
        ImageIcon icon = new ImageIcon(url);
        
        setTitle("My Wallet");
        setIconImage(icon.getImage());
                 
        setResizable(false);
        setVisible(true);
        setLocationRelativeTo(null);
       
        jbtn_save.setEnabled(false);
        jtbl_account.getTableHeader().setReorderingAllowed(false);
    }
    
    public void lauchMessage(String msg){
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public void fillJTable(Object[][] arr){
        
        DefaultTableModel tableModel = (DefaultTableModel) jtbl_account.getModel();
        tableModel.setRowCount(0);
        
        for(Object[] row: arr ){
             tableModel.addRow(row);
        }            
    }
    
    public void fillJcomboBox(ArrayList<String> arr){
        jcbox_type.setModel(new DefaultComboBoxModel(arr.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_account_catch = new javax.swing.JPanel();
        jlbl_number = new javax.swing.JLabel();
        jtf_number = new javax.swing.JTextField();
        jlbl_owner = new javax.swing.JLabel();
        jtf_owner = new javax.swing.JTextField();
        jlbl_balance = new javax.swing.JLabel();
        jspn_balance = new javax.swing.JSpinner();
        jlbl_type = new javax.swing.JLabel();
        jcbox_type = new javax.swing.JComboBox();
        jbtn_save = new javax.swing.JButton();
        jpnl_account_show = new javax.swing.JPanel();
        jscp_account = new javax.swing.JScrollPane();
        jtbl_account = new javax.swing.JTable();
        jbtn_search = new javax.swing.JButton();
        jbtn_close = new javax.swing.JButton();
        jmbar_account = new javax.swing.JMenuBar();
        jmbar_options = new javax.swing.JMenu();
        jmitem_account = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnl_account_catch.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        jlbl_number.setText("Número");

        jlbl_owner.setText("Titular");

        jtf_owner.setEditable(false);

        jlbl_balance.setText("Balance");

        jspn_balance.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));

        jlbl_type.setText("Tipo de Cuenta");

        jcbox_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción" }));

        jbtn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/save.png"))); // NOI18N

        javax.swing.GroupLayout jpnl_account_catchLayout = new javax.swing.GroupLayout(jpnl_account_catch);
        jpnl_account_catch.setLayout(jpnl_account_catchLayout);
        jpnl_account_catchLayout.setHorizontalGroup(
            jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_account_catchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl_account_catchLayout.createSequentialGroup()
                        .addComponent(jlbl_number)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnl_account_catchLayout.createSequentialGroup()
                        .addGroup(jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbl_type)
                            .addComponent(jcbox_type, 0, 140, Short.MAX_VALUE)
                            .addComponent(jtf_number))
                        .addGap(30, 30, 30)
                        .addGroup(jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbl_owner)
                            .addComponent(jlbl_balance)
                            .addComponent(jtf_owner)
                            .addComponent(jspn_balance, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnl_account_catchLayout.setVerticalGroup(
            jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_account_catchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_number)
                    .addComponent(jlbl_owner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl_account_catchLayout.createSequentialGroup()
                        .addGroup(jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_type)
                            .addComponent(jlbl_balance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnl_account_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbox_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspn_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jtbl_account.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Tipo", "Saldo", "Fecha de Creación"
            }
        ));
        jscp_account.setViewportView(jtbl_account);

        jbtn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/search.png"))); // NOI18N
        jbtn_search.setText("Listar");

        jbtn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/close.png"))); // NOI18N
        jbtn_close.setText("Salir");

        javax.swing.GroupLayout jpnl_account_showLayout = new javax.swing.GroupLayout(jpnl_account_show);
        jpnl_account_show.setLayout(jpnl_account_showLayout);
        jpnl_account_showLayout.setHorizontalGroup(
            jpnl_account_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_account_showLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_account_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl_account_showLayout.createSequentialGroup()
                        .addComponent(jscp_account, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnl_account_showLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_close)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnl_account_showLayout.setVerticalGroup(
            jpnl_account_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_account_showLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscp_account, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnl_account_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jmbar_options.setText("Opciones");

        jmitem_account.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmitem_account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/img/minclose.png"))); // NOI18N
        jmitem_account.setText("Salir");
        jmbar_options.add(jmitem_account);

        jmbar_account.add(jmbar_options);

        setJMenuBar(jmbar_account);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnl_account_show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpnl_account_catch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jpnl_account_catch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnl_account_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_close;
    public javax.swing.JButton jbtn_save;
    public javax.swing.JButton jbtn_search;
    public javax.swing.JComboBox jcbox_type;
    private javax.swing.JLabel jlbl_balance;
    private javax.swing.JLabel jlbl_number;
    private javax.swing.JLabel jlbl_owner;
    private javax.swing.JLabel jlbl_type;
    public javax.swing.JMenuBar jmbar_account;
    public javax.swing.JMenu jmbar_options;
    public javax.swing.JMenuItem jmitem_account;
    public javax.swing.JPanel jpnl_account_catch;
    public javax.swing.JPanel jpnl_account_show;
    private javax.swing.JScrollPane jscp_account;
    public javax.swing.JSpinner jspn_balance;
    private javax.swing.JTable jtbl_account;
    public javax.swing.JTextField jtf_number;
    public javax.swing.JTextField jtf_owner;
    // End of variables declaration//GEN-END:variables
}
