/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mvc.view;

/**
 *
 * @author Diego SNP3004EX
 */
public class JFFTransaction extends javax.swing.JFrame {

    /**
     * Creates new form JFFTransaction
     */
    public JFFTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_transaction_catch = new javax.swing.JPanel();
        jlbl_type = new javax.swing.JLabel();
        jcbox_category = new javax.swing.JComboBox();
        jlbl_originacc = new javax.swing.JLabel();
        jlbl_destinyacc = new javax.swing.JLabel();
        jtf_originacc = new javax.swing.JTextField();
        jtf_destinyacc = new javax.swing.JTextField();
        jlbl_concept = new javax.swing.JLabel();
        jcbox_concept = new javax.swing.JComboBox();
        jlbl_amount = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();
        jspn_amount = new javax.swing.JSpinner();
        jpnl_transaction_show = new javax.swing.JPanel();
        jscp_transaction = new javax.swing.JScrollPane();
        jtbl_transaction = new javax.swing.JTable();
        jmbar_transaction = new javax.swing.JMenuBar();
        jmen_options = new javax.swing.JMenu();
        jmitem_close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnl_transaction_catch.setBorder(javax.swing.BorderFactory.createTitledBorder("Transacciones"));

        jlbl_type.setText("Operación");

        jcbox_category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una operación..." }));

        jlbl_originacc.setText("Número de Cuenta");

        jlbl_destinyacc.setText("Cuenta Destino");

        jlbl_concept.setText("Concepto");

        jcbox_concept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una operación..." }));

        jlbl_amount.setText("Monto");

        btn_send.setText("Enviar");

        javax.swing.GroupLayout jpnl_transaction_catchLayout = new javax.swing.GroupLayout(jpnl_transaction_catch);
        jpnl_transaction_catch.setLayout(jpnl_transaction_catchLayout);
        jpnl_transaction_catchLayout.setHorizontalGroup(
            jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_transaction_catchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl_transaction_catchLayout.createSequentialGroup()
                        .addComponent(jlbl_type)
                        .addGap(99, 99, 99)
                        .addComponent(jlbl_originacc))
                    .addGroup(jpnl_transaction_catchLayout.createSequentialGroup()
                        .addGroup(jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbox_category, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_concept)
                            .addComponent(jcbox_concept, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbl_amount)
                            .addComponent(jtf_originacc)
                            .addComponent(jspn_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbl_destinyacc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_destinyacc)
                    .addComponent(btn_send, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnl_transaction_catchLayout.setVerticalGroup(
            jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_transaction_catchLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_type)
                    .addComponent(jlbl_originacc)
                    .addComponent(jlbl_destinyacc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbox_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_originacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_destinyacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_concept)
                    .addComponent(jlbl_amount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnl_transaction_catchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbox_concept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send)
                    .addComponent(jspn_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jtbl_transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Cuenta", "Tipo", "Concepto", "Monto", "Fecha"
            }
        ));
        jscp_transaction.setViewportView(jtbl_transaction);

        javax.swing.GroupLayout jpnl_transaction_showLayout = new javax.swing.GroupLayout(jpnl_transaction_show);
        jpnl_transaction_show.setLayout(jpnl_transaction_showLayout);
        jpnl_transaction_showLayout.setHorizontalGroup(
            jpnl_transaction_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_transaction_showLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscp_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnl_transaction_showLayout.setVerticalGroup(
            jpnl_transaction_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl_transaction_showLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jscp_transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
        );

        jmen_options.setText("Opciones");

        jmitem_close.setText("Salir");
        jmen_options.add(jmitem_close);

        jmbar_transaction.add(jmen_options);

        setJMenuBar(jmbar_transaction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnl_transaction_catch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnl_transaction_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jpnl_transaction_catch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnl_transaction_show, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JComboBox jcbox_category;
    private javax.swing.JComboBox jcbox_concept;
    private javax.swing.JLabel jlbl_amount;
    private javax.swing.JLabel jlbl_concept;
    private javax.swing.JLabel jlbl_destinyacc;
    private javax.swing.JLabel jlbl_originacc;
    private javax.swing.JLabel jlbl_type;
    private javax.swing.JMenuBar jmbar_transaction;
    private javax.swing.JMenu jmen_options;
    private javax.swing.JMenuItem jmitem_close;
    private javax.swing.JPanel jpnl_transaction_catch;
    private javax.swing.JPanel jpnl_transaction_show;
    private javax.swing.JScrollPane jscp_transaction;
    private javax.swing.JSpinner jspn_amount;
    private javax.swing.JTable jtbl_transaction;
    private javax.swing.JTextField jtf_destinyacc;
    private javax.swing.JTextField jtf_originacc;
    // End of variables declaration//GEN-END:variables
}
